### ISSUE TITLE
Results don't match git log output

### ISSUE THREAD

**Issue by lwasyl** [rubberduck203/GitNStats#13]
The app shows some pretty weird results for my repository which has 32270 commits for `develop` branch (counted via `git rev-list --count HEAD`) and 39219 commits for all branches (`git rev-list --count --all`).

Namely, on GitNStats output a file will show ~111 commits, while `git log --follow <<path>>` will only show 3 commits for that file, and `git log --follow --all <<path>>` will show 4 commits. For the most commited file, GitNStats shows 6328 commits, while simple `git log --oneline <<path>> | wc -l` will show "only" 1150.

Is there something I'm misunderstanding about this tool? The repository is pretty specific in that it has lots of long-running branches and many times single branch is merged into multiple others. Still, it feels like the results are way off. Unfortunately I can't share the repository in question

**Comment by rubberduck203** [comment]
It’s entirely possible that I’ve gotten something wrong. I’ve verified results manually against a few small repositories (including against itself) and spot checked against the [Rubberduck VBA repository](https://github.com/rubberduck-vba/Rubberduck/), which has a significant history.  

I’m concerned that there may be a bug, but I don’t have enough to go off of here to reproduce. Is there anything more you can tell me or thoughts on how I might reproduce?

**Comment by rubberduck203** [comment]
I finally had some time to sit down and take a look at this.
I've been able to replicate the behavior you're seeing.

On a hunch, do you happen to use a lot of tags?

**Comment by lwasyl** [comment]
Thanks for the follow up! I haven't had time to explore the issue some more, but here are some numbers for the repository: 25 tags (so I'd say not much), 18 local branches, 486 local + remote branches

**Comment by rubberduck203** [comment]
Ok. So not tags then. I’m thinking there’s a bug in the way I’m “ensuring” we only visit & count each commit once. Essentially, I’m not dead-ending the graph traversal correctly. 

FWIW, the purpose of this tool is to make it easy to get an overview of the entire repository. `rev-list` and `log —follow` make it easy to get the history of any particular file, but it’s difficult to use them to get a summary of *every* file. 

To that end, I believe the tool is currently identifying which files change most and least. It’s just not giving accurate counts. 

Thanks for reaching out. I’m going to keep digging into this and see if I can’t correct it.

**Comment by lwasyl** [comment]
> To that end, I believe the tool is currently identifying which files change most and least

Most likely yes :) 

The repository I'm analyzing has many branches that are being merged to multiple other branches. Perhaps something's off when counting the same commits that happen on multiple branches? Just a wild guess. Fyi I'm now counting ~20k one-parent commits, and ~13k two-parent commits

**Comment by rubberduck203** [comment]
> The repository I'm analyzing has many branches that are being merged to multiple other branches.

Good to know. I’ll add some test cases around that and let you know how it goes.

**Comment by rubberduck203** [comment]
It turns out that I am having trouble replicating this, at least with `git log --follow <<path>>`.
Running GitNStats on this repository returns the same results as running `git log --follow --oneline <<path>> | wc -l` on each file returned by gitnstats.

`git rev-list --count HEAD` is more puzzling. I dumped the gitnstats results to a spread sheet and summed them to get `265` commits (or with `awk`).

```
dotnet run --project src/gitnstats/gitnstats.csproj | awk '{s+=$1}END{print s}'
```

But when I run `git rev-list --count HEAD` or `git log --pretty=oneline | wc -l`, I get `108`.
That is seriously confusing behavior.
When I look up the number of commits per file, they add up to a significantly higher number than the number of commits in the log.

**Comment by rubberduck203** [comment]
D'oh!

Of course summing `git log --follow <<path>>` doesn't match `git rev-list --count head`.
Multiple files can (and are) in a single commit, so (obviously) those numbers won't match.
I was heading down a dead end.

**Comment by rubberduck203** [comment]
I was finally able to replicate the (an?) issue on [the divo repository](https://github.com/smartcitiesdata/divo).

GitNStats output

```console
$ dotnet run --project src/gitnstats/gitnstats.csproj -- ~/src/smartcity/divo/

Repository: /Users/rubberduck/src/smartcity/divo/
Branch: master

Commits Path
53      mix.exs
35      README.md
```

git log output

```console
$ git log --follow --oneline mix.exs  | wc -l
      33
$ git log --follow --oneline README.md | wc -l
      22
```

**Comment by rubberduck203** [comment]
I think this has something to do with merge commits.
It seems that `git log` will show all merge commits in the history, but `git log <<path>>` excludes merge commits, resulting in a lower number.
I *believe* GitNStats is behaving the way `git log` without a path does.

As a concrete example, for divo, `git log` picks up 8f7d9836f, but `git log mix.exs` does not.

**Comment by rubberduck203** [comment]
AHA!

```console
$ git log --oneline --full-history mix.exs | wc -l
      53
```

This stackoverflow answer gave me the hint I needed.
https://stackoverflow.com/a/10181681/3198973

The behavior is described in [the git log manual under History Simplification](https://git-scm.com/docs/git-log#_history_simplification).

I'm too tired to grok it or to decide on whether or not this is a bug right now, but `gitnstats` is counting the number of commits correctly, i.e. there is no race condition when walking the tree and it is correctly terminating when walking the graph.

@lwasyl I know it's been a long time, but could you try using `--full-history` when you run the `git log`?

**Comment by rubberduck203** [comment]
I've decided that `gitnstats` should default to the same default history simplification as git and add an additional option for `--full-history`.
As of this moment, I'm unsure of how to access or implement the default history simplification.

I have discovered that `rev-list` uses the same history simplification as `log` though (not surprising really, but I'm hoping that I can leverage that fact to implement).

```sh
git rev-list --count head -- mix.exs
git rev-list --full-history --count head -- mix.exs
```

**Comment by rubberduck203** [comment]
I did some digging around in libgit2 and libgit2sharp. After several hours I reached out to Edward Thompson and had this brief conversation. 

https://twitter.com/rubberduck203/status/1181750623060086784?s=21

Long story short, I’ll need to re-implement history simplification myself.

**Comment by rubberduck203** [comment]
I've thought about this a lot and I would be happy to accept a pull request that addresses this, but the tool meets my needs as is and I won't be attempting to make this change myself.
