### ISSUE TITLE
Update to .Net Core 3.1

### ISSUE THREAD

**Issue by rubberduck203** [rubberduck203/GitNStats#14]
GitNStats is still on .Net Core 1.1

**Comment by psmorandi** [comment]
Hello there, I did the migration, but don't know how to push here. I created a branch and I guess I have no permission to push it so you guys could review it and merge it. It was quite simple to migrate. It's just the projects and the publish.sh. Everything else seems fine. If you like, I could email or put it here.

ps.: Only thing, one unit test is breaking to me:
```C#
[Fact] public void GivenTimeInESTAndCommitWasInADT_ReturnsFalse()
{
    var commit = Commit().WithAuthor(DateTimeOffset.Parse("2017-06-21 13:30 -3:00"));
    var predicate = OnOrAfter(new DateTime(2017, 6, 21, 13, 30, 0, DateTimeKind.Local));
    Assert.False(predicate(Diff(commit)));
}
```
Well, I'm in -3 UTC, so I guess this is the problem, because the 2 dates compared are indeed equals in my machine.

**Comment by rubberduck203** [comment]
Wow! Thanks @psmorandi!
I suspect the unit test is failing because I used `DateTimeKind.Local`.
I can fix that. Thanks for pointing it out.

I'm assuming that you cloned the repo and created a branch.
Let's see if I can't walk you through submitting a pull request.

First, fork this repository following [these instructions](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo). It basically boils down to clicking the "fork" button.

Next, we'll need to update the remotes for your local copy.
Let's check to see what the current `origin` is, I'm thinking it should look like this right now.

```console
$ git remote -v
origin	https://github.com/rubberduck203/GitNStats.git (fetch)
origin	https://github.com/rubberduck203/GitNStats.git (push)
```

If that's what you're seeing, we'll rename it to `upstream`.

```console
$ git remote rename origin upstream
```

Then add your new fork as the new `origin`.

```console
$ git remote add origin https://github.com/psmorandi/GitNStats.git
$ git remote -v
origin	https://github.com/psmorandi/GitNStats.git (fetch)
origin	https://github.com/psmorandi/GitNStats.git (push)
upstream	https://github.com/rubberduck203/GitNStats.git (fetch)
upstream	https://github.com/rubberduck203/GitNStats.git (push)
```

Now you can push your changes to your fork.

```console
$ git push -u origin your_branch
```

Finally, you can [submit a pull request](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request).
This link should take you directly to where you can create it.
https://github.com/rubberduck203/GitNStats/compare


If you're more comfortable creating a patch file with `git format-patch`, you could just post it here in a code block.

**Comment by psmorandi** [comment]
Sorry for that, I didn't know that I must make a fork of repo before. I found some instructions from github itself, I did it right now, I hope. Thanks for the attention.

**Comment by rubberduck203** [comment]
Please don’t be sorry at all. I appreciate you doing this. I should have time to sit down and review the changes tomorrow.

**Comment by rubberduck203** [comment]
Just published the release.
https://github.com/rubberduck203/GitNStats/releases/tag/2.2.0
